
$cflags = "-g -Wall -std=c99 ../libhivem.a -I../include -liconv #{`pkg-config --libs glib-2.0`.strip}"

task 'default' => ['test_vm']

desc "Build VM tester"
file 'test_vm' => ['test_vm.c'] do
  sh "cc test_vm.c #{$cflags} -o test_vm"
end

desc 'Clean'
task 'clean' do
  sh "rm test_vm"
end
