language: c
compiler: clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get -q install libc6-dev protobuf-c-compiler libprotobuf-c0-dev libprotobuf-c0 lua5.1 liblua5.1-0-dev
 - sh setup-jemalloc.sh
 - cd deps/jemalloc-3.6.0 && sudo make install
install: gem install rake
script: rake
