
$llvm_config = 'llvm-config'
if `uname -s`.strip == 'Darwin'
  $llvm_config = "#{`brew --prefix llvm`.strip}/bin/llvm-config"
end

$llvm_ldflags = `#{$llvm_config} --system-libs --cflags --ldflags --libs core analysis executionengine jit mcjit interpreter native`.gsub("\n", ' ').strip
$llvm_cflags = `#{$llvm_config} --cflags`.strip

$cflags  = "-g -Wall -std=c99 -I../../include #{`pkg-config --cflags glib-2.0 lua5.1`.strip} #{$llvm_cflags}"
$ldflags = "../../libhivm-db.a -liconv #{`pkg-config --libs glib-2.0 lua5.1`.strip} #{$llvm_ldflags}"

task 'default' => ['test_sorting']

desc 'Build VM tester object'
file 'test_sorting.o' => ['test_sorting.c', '../../libhivm-db.a'] do
  sh "clang #{$cflags} -c test_sorting.c"
end

desc 'Build VM tester executable'
file 'test_sorting' => ['test_sorting.o'] do |t|
  sh "clang++ #{t.prerequisites.first} #{$ldflags} -o #{t.name}"
end

desc 'Clean'
task 'clean' do
  sh 'rm -f test_sorting'
end
