
$cflags  = "-g -Wall -std=c99 -I../../include #{`pkg-config --cflags glib-2.0 lua5.1`.strip}"
$ldflags = "../../libhivm-db.a -liconv -lz -lcurses -ljemalloc #{`pkg-config --libs glib-2.0 lua5.1`.strip} -dead_strip"

task 'default' => ['test_sorting']

desc 'Build VM tester object'
file 'test_sorting.o' => ['test_sorting.c', '../../libhivm-db.a'] do
  sh "clang #{$cflags} -c test_sorting.c"
end

desc 'Build VM tester executable'
file 'test_sorting' => ['test_sorting.o'] do |t|
  sh "clang++ #{t.prerequisites.first} #{$ldflags} -o #{t.name}"
end

desc 'Clean'
task 'clean' do
  sh 'rm -f test_sorting'
end
