
$cflags = "-g -Wall -std=c99 ../../libhivm-db.a -I../../include #{`pkg-config --cflags glib-2.0 lua5.1`.strip} -liconv #{`pkg-config --libs glib-2.0 lua5.1`.strip}"

task 'default' => ['test_vm']

desc "Build VM tester"
file 'test_vm' => ['test_vm.c', '../../libhivm-db.a'] do
  sh "cc test_vm.c #{$cflags} -o test_vm"
end

desc 'Clean'
task 'clean' do
  sh "rm test_vm"
end
