
$cflags = "-g -Wall -std=c99 -I../../include"
$ldflags = "../../libhivm-db.a -liconv -lz -lcurses #{`pkg-config --libs glib-2.0 lua5.1`.strip} -dead_strip"

test_bins = []

tests = Dir['test_*.c']
tests.each do |src|
  bin = src.sub '.c', ''
  obj = src.sub '.c', '.o'
  # Add it to the list of generated test binaries
  test_bins << bin

  desc "Build #{bin} test binary"
  file bin => [src, 'preamble.h'] do |t|
    sh "clang -c #{src} #{$cflags}"
    sh "clang++ #{obj} #{$ldflags} -o #{bin}"
  end
end

desc 'Build all tests'
task 'build' => test_bins

desc 'Run all tests'
task 'default' => ['build'] do |t|
  passed = []
  failed = []
  total  = 0
  test_bins.each do |bin|
    Open3.popen3("./#{bin}") {|stdin, stdout, stderr, wait|
      stdout.each_char {|c|
        # Skip newlines
        next if c == "\n"
        print c
      }
      # TODO: Collect errors from stderr via `stderr.each_line`
      status = wait.value
      if status.exitstatus == 0
        passed << bin
      else
        failed << bin
      end
      total += 1
    }
  end
  puts "\n\n"
  # Print summary
  puts "Total: #{total.to_s} tests"
  puts "Pass: #{passed.length}, fail: #{failed.length}."
end

desc 'Clean'
task 'clean' do
  sh "rm -f #{test_bins.join ' '}"
end
